export const WEATHER_REQUEST = 'WEATHER_REQUEST'
export const WEATHER_RESPONSE = 'WEATHER_RESPONSE'

export const BULBS_REQUEST = 'BULBS_REQUEST'
export const BULBS_RESPONSE = 'BULBS_RESPONSE'

export const ROOMS_REQUEST = 'ROOMS_REQUEST'
export const ROOMS_RESPONSE = 'ROOMS_RESPONSE'

export const BULB_TOGGLE_REQUEST = 'BULB_TOGGLE_REQUEST'
export const BULB_TOGGLE_RESPONSE = 'BULB_TOGGLE_RESPONSE'
